### ISSUE TITLE
Issues with whitelist and samplesheet

### ISSUE THREAD

**Issue by JoBerger99** [GoekeLab/bambu-singlecell-spatial#5]
Hey,

I have ran into two small issues. I circumvented them in my own analysis, but I wanted to bring them up here so they can be fixed, if needed, for the whole pipeline. So I have ran the pipeline using 10x5'v3 single cell data with a custom whitelist (fitting the chemistry) and a samplesheet. 

First issue: The whitelist is used in the spatial flag of the bambu step, which leads to an error since it is not a spatial whitelist. I deleted the spatial flag and it works now. Seems like the spatial argument is active despite the --spatial flag not set. 

This was the error:  
--- Start calculating equivilance classes ---
  Error: BiocParallel errors
    1 remote errors, element index: 1
    0 unevaluated and other errors
    first remote error:
  Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 1 did not have 3 elements
  Execution halted
  
And I could circumvent it by deleting "spatial = $whitelist" in line 175 of main.nf. 
And to that point. It only worked if I put $whitelist in "$whitelist". I think this was a small bug, since the other variables are also called like this.

The second issue: This I could only circumvent by not using a samplesheet and rather processing samples individually. When using a sample sheet like this [Example_Samplesheet.csv](https://github.com/user-attachments/files/17163289/Example_Samplesheet.csv). I get this error in the EM Step: 

 --- Start calculating equivilance classes ---
  Error in if (file == "") file <- stdout() else if (is.character(file)) { : 
    the condition has length > 1
  Calls: writeBambuOutput -> writeToGTF -> <Anonymous>
  Execution halted

  
 Let me know if you need further information. 
  
 Thanks, Jonas

**Comment by andredsim** [comment]
Thanks Jonas. Sorry with all the hassle using it so far and I appreciate your diligent troubleshooting!

I believe I have fixed the $whitelist issue thanks to your comment. It was reading in the whitelist argument as the string "FALSE" instead of the logical and made it dependent on the spatial flag (which wasn't even used previously). Please let me know if that is resolved for you.

Second issue was due to how I recently changed the lowMemory mode. When lowMemory mode wasn't on it was trying to provide multiple sample names to the bambu output for the first quant step, when there is only 1 output. I hope I have resolved this now too.

I have pushed these changes. Please let me know if it resolves your issues, and do let me know if any more arise ( likely :) ).

Kind Regards,
Andre Sim

**Comment by JoBerger99** [comment]
Hi Andre, 
Thanks for your quick fixes to these problems. It is working since your changes.
So far I have not encountered any others isses regarding the pipeline.

Best, 
Jonas
